### ISSUE TITLE
Consider submitting to packagist?

### ISSUE THREAD

**Issue by MrHuli** [jamesrwilliams/wp-feature-flags#17]
As this plugin isn't in the official wordpress plugin directory it doesn't get mirrored on [wpackagist](https://wpackagist.org/), which is fair enough. However, any chance of submitting to regular [packagist](https://packagist.org/) for ease of install with composer?

**Comment by jamesrwilliams** [comment]
Hi @MrHuli, thanks for the suggestion, the long term plan is to get this on the WordPress plugin directory but in the meantime, it is now available on packagist as `jamesrwilliams/wp-feature-flags`

```
composer require jamesrwilliams/wp-feature-flags
```
