### ISSUE TITLE
Allow users to enable features for all users

### ISSUE THREAD

**Issue by jamesrwilliams** [jamesrwilliams/wp-feature-flags#2]
An administrator should be able to toggle a feature for all users of their site via the admin area.

**Comment by jamesrwilliams** [comment]
This is the next thing I want to start work on, and I'm considering adding a configuration option to the flag that enables this functionality. 

Just imagining a situation of having an "alpha" state flag which is accidentally enabled using this functionality breaking the site. On the flipside, I don't want to make the configuration overly complex.

**Comment by jamesrwilliams** [comment]
I've finally started working on this and will be doing so on [feat/global-toggle](https://github.com/jamesrwilliams/wp-feature-flags/tree/feat/global-toggle). I'm having a tough time to name these actions, so far I've come up with the following names:

- *Preview* - When a user enables it within their own admin area for them to preview.
- *Publish* - Enable the flag for everyone visiting the site. 
- *???* - To enable a feature to be used via a query string. (Very open to suggestions on this)

**Comment by thelevicole** [comment]
Could call the last one “Conditional” ? ¯\_(ツ)_/¯

**Comment by jamesrwilliams** [comment]
I'm thinking of breaking the whole query string thing into a separate action. Then you can manage them separately (and the potential groups idea #12) without having to "preview" it.

**Comment by jamesrwilliams** [comment]
I've got a basic implementation of this live on develop at the moment if anyone wants to take a look. I've also introduced the `stable` parameter to make sure users can only publish features that are "stable" no trigger happy admins launching some half-finished code.

**Comment by jamesrwilliams** [comment]
I'm going to close this as the basic implementation is now working.
